apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: discovery-server
  name: discovery-server
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        -
          image: jjenksy/eureka-server
          imagePullPolicy: IfNotPresent
          name: discovery-server
          ports:
            - name: springboot-app
              containerPort: 8761
          livenessProbe:
                      httpGet:
                          path: /actuator/health
                          port: springboot-app
                      initialDelaySeconds: 180
                      periodSeconds: 10
          readinessProbe:
                      httpGet:
                          path: /actuator/health
                          port: springboot-app
                      initialDelaySeconds: 15
                      periodSeconds: 3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: APP_NAME
              value: discovery-server
            - name: LOGLEVEL
              value: DEBUG
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: default
spec:
  ports:
    -
      port: 8761
      targetPort: 8761
  selector:
    app: discovery-server
  type: NodePort